baseURL="http://localhost:1313/"
locale = "ko-kr"
title = "Blog for Yongjun Choi"
disableKinds = ["taxonomy", "term"]

[params]
	description = "Yongjun Choi's personal homepage built with Hugo"
	math = true