name = "Yongjun-blog"
compatibility_date = "2026-05-13"

[site]
bucket = "./public" # Hugo의 기본 출력 폴더는 public입니다.

[build]
command = "chmod +x build.sh && ./build.sh"
# Pages 전용 출력 디렉토리 설정 (Wrangler v3 이상 권장)
pages_build_output_dir = "public"